import Navbar from '@/components/Navbar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/global.css';
import Footer from '@/components/Footer';
import ThemeRegistry from '@/styles/theme/ThemeRegistry';
import ResponsiveAppBar from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Gestão | Vida Agroecológica',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <ThemeRegistry>
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </ThemeRegistry>
    </html>
  );
}
